### ISSUE TITLE
awk syntax error at PE version check

### ISSUE THREAD

**Issue by natemccurdy** [GeoffWilliams/puppet-preflight#1]
Seeing the following error on Ubuntu 14.04. This occurs duing the check for EXISTING_PE_VERSION.

```
awk: 1: unexpected character '\'
```

For lack of troubleshooting awk syntax, I used this to get around it:

```
EXISTING_PE_VERSION=$(echo $EXISTING_PE | awk '{print $4}' | sed 's/)//')
```

**Comment by GeoffWilliams** [comment]
thanks nate!  I haven't had chance to maintain this script for a while but I'll have a look at this if I do any updates
